[package]
name = "ribozyme"
version = "0.3.0"
authors = ["Boomber <boomberisalreadytaken@gmail.com>"]
edition = "2018"
description = "Catalyst for merging resourcepacks"
homepage = "https://github.com/oOBoomberOo/ribozyme"
repository = "https://github.com/oOBoomberOo/ribozyme"
readme = "README.md"
keywords = ["resourcepack", "merger", "ribozyme", "minecraft"]
categories = ["command-line-utilities"]
license = "MIT"

[badges]
maintenance = { status = "experimental" }

[dependencies]
colored = "1.9.3"
dialoguer = "0.5.0"
indicatif = "0.14.0"
clap = { version = "2.33.0", features = ["yaml"] }
serde_json = "1.0.48"
serde = { version = "1.0.104", features = ["derive"] }
tempfile = "3.1.0"
regex = "1.3.4"
rayon = "1.3.0"
tar = "0.4.26"
flate2 = "1.0.13"