[package]
name = "ribozyme"
version = "0.2.0"
authors = ["boomber"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
console = "0.9.2"
dialoguer = "0.5.0"
indicatif = "0.14.0"
clap = { version = "2.33.0", features = ["yaml"] }
zip = "0.5.4"
serde_json = "1.0.48"
serde = { version = "1.0.104", features = ["derive"] }
tempfile = "3.1.0"