[package]
name = "ribozyme"
version = "0.1.1"
authors = ["boomber"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33.0"
zip = "0.5.3"
serde = { version = "1.0.102", features = ["derive"] }
serde_json = "1.0.41"
colored = "1.8.0"
walkdir = "2.2.9"